PCB: false
batchsize: 32
circle: false
color_jitter: false
data_dir: F:\Data\Market-1501
droprate: 0.5
erasing_p: 0
fp16: true
gpu_ids: '0'
lr: 0.05
name: ft_ResNet50
nclasses: 1
stride: 2
train_all: false
use_NAS: false
use_dense: false
warm_epoch: 0
